Repository AY2324S1-CS2103T-W17-1/tp, pull requests merged in 2023-11, with the labels that each got.

#130 Update Create and Storage DG
  docs/DeveloperGuide.md
  docs/diagrams/CreateCommandParse.puml
  docs/diagrams/CreateSequenceDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
Labels: priority.High

#133 Update Developer Guide
  docs/AboutUs.md
  docs/DevOps.md
  docs/DeveloperGuide.md
  docs/SettingUp.md
  docs/Testing.md
  docs/UserGuide.md
  docs/_markbind/layouts/default.md
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/index.md
  docs/team/javinchua.md
  docs/team/jinyang628.md
  docs/team/s-kybound.md
  docs/tutorials/TracingCode.md
Labels: type.Documentation, priority.High

#129 Rectify bugs in the create command
  build.gradle
  docs/team/jinyang628.md
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/CreateCommand.java
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/commands/exceptions/CommandException.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/CreateCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/internship/ApplicationStatus.java
  src/main/java/seedu/address/model/internship/CompanyName.java
  src/main/java/seedu/address/model/internship/Deadline.java
  src/main/java/seedu/address/model/internship/Duration.java
  src/main/java/seedu/address/model/internship/Internship.java
  src/main/java/seedu/address/model/internship/Role.java
  src/main/java/seedu/address/model/internship/StartDate.java
  src/main/java/seedu/address/model/internship/UniqueInternshipList.java
  src/main/java/seedu/address/model/internship/exceptions/DuplicateInternshipException.java
  src/main/java/seedu/address/model/requirement/Requirement.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/java/seedu/address/ui/InternshipMainWindow.java
  src/main/resources/view/InternshipMainWindow.fxml
  src/test/java/seedu/address/commons/util/JsonUtilTest.java
  src/test/java/seedu/address/logic/commands/CreateCommandTest.java
  src/test/java/seedu/address/logic/parser/CommandInternshipParserUtilTest.java
  src/test/java/seedu/address/logic/parser/CreateCommandParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
  src/test/java/seedu/address/logic/parser/FilterCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ModifyCommandParserTest.java
  src/test/java/seedu/address/logic/parser/SortCommandParserTest.java
  src/test/java/seedu/address/model/internship/ApplicationStatusContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/internship/ApplicationStatusTest.java
  src/test/java/seedu/address/model/internship/CompanyNameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/internship/CompanyNameTest.java
  src/test/java/seedu/address/model/internship/DeadlineTest.java
  src/test/java/seedu/address/model/internship/DeadlineWithinRangePredicateTest.java
  src/test/java/seedu/address/model/internship/DurationTest.java
  src/test/java/seedu/address/model/internship/DurationWithinRangePredicateTest.java
  src/test/java/seedu/address/model/internship/InternshipTest.java
  src/test/java/seedu/address/model/internship/RequirementContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/internship/RoleContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/internship/RoleTest.java
  src/test/java/seedu/address/model/internship/StartDateTest.java
  src/test/java/seedu/address/model/internship/StartDateWithinRangePredicateTest.java
  src/test/java/seedu/address/model/internship/UniqueInternshipListTest.java
  src/test/java/seedu/address/model/requirement/RequirementTest.java
  src/test/java/seedu/address/storage/InternshipStorageManagerTest.java
  src/test/java/seedu/address/storage/JsonAdaptedInternshipTest.java
  src/test/java/seedu/address/storage/JsonInternshipBookStorageTest.java
  src/test/java/seedu/address/storage/JsonSerializableInternshipBookTest.java
  src/test/java/seedu/address/testutil/InternshipBuilder.java
Labels: priority.High

#192 Rectify errors in UG from PE
  docs/UserGuide.md
  docs/images/Ui.png
  docs/team/jinyang628.md
Labels: priority.High

#191 Fix create command bugs in PE
  src/main/java/seedu/address/Main.java
  src/main/java/seedu/address/model/internship/CompanyName.java
  src/main/java/seedu/address/model/internship/Role.java
  src/main/java/seedu/address/model/requirement/Requirement.java
  src/test/java/seedu/address/model/internship/CompanyNameTest.java
  src/test/java/seedu/address/model/internship/RoleTest.java
  src/test/java/seedu/address/model/requirement/RequirementTest.java
  src/test/java/seedu/address/storage/JsonAdaptedInternshipTest.java
Labels: priority.High

#202 Update UG
  docs/UserGuide.md
  docs/images/delete.png
Labels: type.Documentation, priority.High

#200 Edited User Guide's "Modify" section
  docs/UserGuide.md
  docs/images/Modify.png
Labels: priority.Medium

#206 Update Delete Image
  docs/UserGuide.md
  docs/images/delete.png
Labels: type.Documentation, priority.High

#208 Resolve issue with Delete Picture
  docs/images/delete.png
Labels: type.Documentation, priority.High

#210 Update target users in UG
  docs/UserGuide.md
  docs/images/create.png
Labels: priority.High

#211 Update DG to include testing of CREATE
  docs/DeveloperGuide.md
  src/main/java/seedu/address/model/internship/ApplicationStatus.java
  src/main/java/seedu/address/model/internship/Deadline.java
  src/main/java/seedu/address/model/internship/Duration.java
  src/main/java/seedu/address/model/internship/StartDate.java
Labels: priority.High

#214 Rectify create command image and message
  docs/images/create.png
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/CreateCommand.java
Labels: priority.High

#225 Update UG parameter constraints error
  docs/UserGuide.md
Labels: priority.High

#231 Standardise referral to entries as internship entries
  docs/UserGuide.md
Labels: type.Documentation, priority.Medium

#229 Update data file information in UG
  docs/UserGuide.md
Labels: priority.High

#236 Update user stories in DG
  docs/DeveloperGuide.md
Labels: type.Documentation, priority.High

#247 Fix UML bug in Storage component
  docs/DeveloperGuide.md
  docs/diagrams/CreateCommandExecute.puml
  docs/diagrams/CreateCommandParse.puml
  docs/diagrams/CreateCommandStore.puml
  docs/diagrams/CreateSequenceDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/team/jinyang628.md
Labels: priority.High

#254 Update DG: Kyriel
  docs/DeveloperGuide.md
  docs/diagrams/DeleteCommandExecute.puml
  docs/diagrams/DeleteCommandParse.puml
  docs/diagrams/DeleteCommandRemove.puml
  docs/diagrams/DeleteSequenceDiagram.puml
Labels: type.Documentation, priority.High

#255 Fix Create Command UML diagram problems
  docs/DeveloperGuide.md
  docs/diagrams/CreateCommandExecute.puml
  docs/diagrams/CreateCommandParse.puml
  docs/diagrams/CreateCommandStore.puml
  docs/diagrams/CreateSequenceDiagram.puml
  docs/team/jinyang628.md
Labels: priority.High

#257 Rectify component naming errors
  docs/DeveloperGuide.md
  docs/diagrams/CreateSequenceDiagram.puml
Labels: priority.High

#259 Trim UML Diagram details
  docs/diagrams/CreateCommandParse.puml
  docs/diagrams/CreateSequenceDiagram.puml
Labels: priority.High

#264 Update UG Markdown error
  docs/UserGuide.md
Labels: priority.High

#266 Remove excess spaces from requirements
  src/main/java/seedu/address/logic/parser/ParserUtil.java
Labels: priority.High

#268 Update Documentation and Refactor Status Bar
  docs/team/s-kybound.md
  src/main/java/seedu/address/logic/commands/FilterCommand.java
  src/main/java/seedu/address/logic/parser/FilterCommandParser.java
  src/main/java/seedu/address/model/InternshipModelManager.java
  src/main/java/seedu/address/ui/InternshipMainWindow.java
  src/main/java/seedu/address/ui/PredicateComparatorDisplay.java
Labels: priority.High

#274 Ug final
  docs/DeveloperGuide.md
  docs/diagrams/ComponentManagers.puml
  docs/diagrams/CreateSequenceDiagram.puml
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/FilterSequenceDiagram.puml
  docs/diagrams/ModifySequenceDiagram.puml
  docs/diagrams/SortSequenceDiagram.puml
Labels: type.Documentation, priority.High

#276 Make Requirements case-insensitive
  src/main/java/seedu/address/logic/parser/ParserUtil.java
Labels: priority.High

#277 Update DG (penultimate)
  docs/DeveloperGuide.md
  docs/diagrams/ModifyCommandExecute.puml
  docs/diagrams/ModifySequenceDiagram.puml
Labels: type.Documentation, priority.High

#278 Final DG update
  docs/DeveloperGuide.md
  docs/diagrams/ModelClassDiagram.puml
  docs/team/s-kybound.md
Labels: type.Documentation, priority.High

#279 Final Update to PPP
  docs/team/s-kybound.md
Labels: type.Documentation, priority.Medium

#284 fix diagram
  docs/diagrams/LogicClassDiagram.puml
Labels: type.Documentation, priority.High
