Repository AY2324S1-CS2103T-W17-1/tp, pull requests merged in 2023-10, with the labels that each got.

#36 Update User Guide (Create Command)
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/CreateCommand.java
Labels: documentation

#56 modifyFunction
  docs/UserGuide.md
Labels: documentation

#43 edited PPP for week 7
  docs/AboutUs.md
  docs/UserGuide.md
  docs/team/yongning.md
  docs/team/yongning0310.md
Labels: documentation

#63 Write test cases to test the Create Command
  docs/team/jinyang628.md
  src/test/java/seedu/address/logic/commands/CreateCommandTest.java
Labels: priority.High

#68 Include test cases for storage
  src/main/java/seedu/address/model/internship/Internship.java
  src/main/java/seedu/address/model/requirement/Requirement.java
  src/main/java/seedu/address/storage/JsonAdaptedInternship.java
  src/test/data/JsonInternshipBookStorageTest/invalidAndValidInternshipInternshipBook.json
  src/test/data/JsonInternshipBookStorageTest/invalidInternshipInternshipBook.json
  src/test/data/JsonInternshipBookStorageTest/notJsonFormatInternshipBook.json
  src/test/data/JsonInternshipUserPrefsStorageTest/EmptyInternshipUserPrefs.json
  src/test/data/JsonInternshipUserPrefsStorageTest/ExtraValuesInternshipUserPref.json
  src/test/data/JsonInternshipUserPrefsStorageTest/NotJsonFormatInternshipUserPrefs.json
  src/test/data/JsonInternshipUserPrefsStorageTest/TypicalInternshipUserPref.json
  src/test/data/JsonSerializableInternshipBookTest/duplicateInternshipInternshipBook.json
  src/test/data/JsonSerializableInternshipBookTest/invalidInternshipInternshipBook.json
  src/test/data/JsonSerializableInternshipBookTest/typicalInternshipsInternshipBook.json
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/storage/InternshipStorageManagerTest.java
  src/test/java/seedu/address/storage/JsonAdaptedInternshipTest.java
  src/test/java/seedu/address/storage/JsonInternshipBookStorageTest.java
  src/test/java/seedu/address/storage/JsonInternshipUserPrefsStorageTest.java
  src/test/java/seedu/address/storage/JsonSerializableInternshipBookTest.java
  src/test/java/seedu/address/testutil/InternshipBuilder.java
  src/test/java/seedu/address/testutil/TypicalInternships.java
Labels: priority.High

#96 Insert create command section in DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/CreateCommandExecute.puml
  docs/diagrams/CreateCommandParse.puml
  docs/diagrams/CreateCommandStore.puml
  docs/team/jinyang628.md
  src/main/java/seedu/address/model/InternshipModel.java
Labels: priority.High

#118 fixed UI
  src/main/java/seedu/address/ui/InternshipCard.java
Labels: type.Bug

#119 Issue 73 filtersortstatus
  src/main/java/seedu/address/logic/InternshipLogic.java
  src/main/java/seedu/address/logic/InternshipLogicManager.java
  src/main/java/seedu/address/logic/commands/FilterCommand.java
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/parser/FilterCommandParser.java
  src/main/java/seedu/address/model/InternshipModel.java
  src/main/java/seedu/address/model/InternshipModelManager.java
  src/main/java/seedu/address/ui/InternshipMainWindow.java
  src/main/java/seedu/address/ui/PredicateComparatorDisplay.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/InternshipMainWindow.fxml
  src/main/resources/view/PredicateComparatorDisplay.fxml
  src/test/java/seedu/address/logic/commands/CreateCommandTest.java
Labels: type.Enhancement, priority.High

#120 Update PPP
  docs/team/s-kybound.md
Labels: type.Documentation, priority.Medium

#116 Implement shared elements of UG
  docs/UserGuide.md
  docs/team/jinyang628.md
  src/main/java/seedu/address/Main.java
  src/main/java/seedu/address/logic/parser/CreateCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/internship/ApplicationStatus.java
  src/main/java/seedu/address/model/internship/ApplicationStatusContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/internship/CompanyName.java
  src/main/java/seedu/address/model/internship/Internship.java
  src/main/java/seedu/address/model/internship/Role.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/SortCommandTest.java
  src/test/java/seedu/address/logic/parser/InternshipBookParserTest.java
  src/test/java/seedu/address/model/InternshipBookTest.java
  src/test/java/seedu/address/model/internship/ApplicationStatusContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/internship/CompanyNameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/internship/DeadlineWithinRangePredicateTest.java
  src/test/java/seedu/address/model/internship/DurationWithinRangePredicateTest.java
  src/test/java/seedu/address/model/internship/InternshipTest.java
  src/test/java/seedu/address/model/internship/RequirementContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/requirement/RequirementTest.java
  src/test/java/seedu/address/testutil/InternshipUtil.java
Labels: priority.High
